# Generated by Django 5.1.1 on 2025-12-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skuska', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='datum',
            field=models.DateField(),
        ),
    ]
